# -*- coding: utf-8 -*-
"""python_mega_assessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZamlZV98n50k-r00AnTVMMFR9ugFJU7i

**Q26. What is a string? How can we declare string in Python?**

**String is the datatype in python just like char in java , it is a sequence of character ** 
we can declare string as:
"""

str1 = "nikita"
print(str1)

"""**Q27. How can we access the string using its index?**

"""

list1 = ["preeta" , "nikita " , "hema ", "geeta"]
print(list1[1])
print(type(list1[1]))

"""**Q28. Write a code to get the desired output of the following**

string = "Big Data iNeuron"

desired_output = "iNeuron"





"""

string = "Big Data iNeuron"
print(string[9 :16])

"""**Q29. Write a code to get the desired output of the following**

string = "Big Data iNeuron"

desired_output = "norueNi"

"""

string =( "Big Data iNeuron")
print(string[ :8: -1])

"""**Q30. Resverse the string given in the above question.**

string = "Big Data iNeuron"


"""

print(string[ : : -1])

"""**Q31. How can you delete entire string at once? **"""

string =( "Big Data iNeuron")
del(string)

"""**Q32. What is escape sequence?**

An escape sequence is a sequence of characters that, when used inside a character or string, does not represent itself but is converted into another character or series of characters that may be difficult or impossible to express directly, like newline (\n), tab (\t), and so on.
"""

print("my name is \" khan \" ")

"""**Q33. How can you print the below string?**

**'iNeuron's Big Data Course'**
"""

print (" 'iNeuron's Big Data Course'")

"""**Q34. What is a list in Python?**

list is the data type in python which excepts all value of all type .
Lists are used to store multiple items in a single variable. Lists are one of 4 built-in data types in Python used to store collections of data, the other 3 are Tuple, Set, and Dictionary, all with different qualities and usage.

**Q35. How can you create a list in Python?**
"""

list1 = []
list1.append("nikita")
print(list1)


list2 = ["nikita" , "sherki ", "23" , "cse","capgemini"]
print(list2)

"""**Q36. How can we access the elements in a list?**

 we can access element in the list by using indexing .for example -
"""

list2 = ["nikita" , "sherki ", "23" , "cse","capgemini"]
print(list2[0])
list2.append("realme6")
print(list2)

"""**Q37. Write a code to access the word "iNeuron" from the given list.**

**lst = [1,2,3,"Hi",[45,54, "iNeuron"], "Big Data"]**
"""

lst = [1,2,3,"Hi",[45,54, "iNeuron"], "Big Data"]
print(lst[4][2])

"""**Q38. Take a list as an input from the user and find the length of the list.**


"""

lst = list(input(" list1"))
print(len(lst))

"""**Q39. Add the word "Big" in the 3rd index of the given list.**"""

lst = ["Welcome", "to", "Data", "course"]
lst.insert(2,"Big")
print(lst)

"""**Q40. What is a tuple? How is it different from list?**
Tuple is  data structure in python . represented by ().
The primary difference between tuples and lists is that tuples are immutable as opposed to lists which are mutable. Therefore, it is possible to change a list but not a tuple.

**Q41. How can you create a tuple in Python?**
"""

tuple1 = ("my name is arina " , "i am  23 years old ")
print(tuple1)
tuple1 = list(tuple1)
tuple1.append("i am a fan of mostly sane a youtuber")
print(tuple1)

"""**Q42. Create a tuple and try to add your name in the tuple. Are you able to do it? Support your answer with reason.**

 
 i cannot add my name to the given tuple because tuple are immutable we can not perform add , inset, appen ddel etc operation on tuple its is static ,

 to modify tuple , we need to cnvert tuple into list then we can modify it .
"""

tuple1 = ("my name is arina " , "i am  23 years old ")
print(tuple1)
tuple1 = list(tuple1)
tuple1.append("i am a fan of mostly sane a youtuber")
print(tuple1)

"""**Q43. Can two tuple be appended. If yes, write a code for it. If not, why?**

--> same as sns number 42.

**Q44. Take a tuple as an input and print the count of elements in it.**
"""

tuple1 = (input("insert tuple"))
print(tuple1)

"""**Q45. What are sets in Python?**

Set is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Tuple, and Dictionary, all with different qualities and usage. A set is a collection which is unordered, unchangeable*, and unindexed. * Note: Set items are unchangeable, but you can remove items and add new items.

**Q46. How can you create a set?**
"""

set1 = {123,123,123,234,235,356}
print(set1)

"""**Q47. Create a set and add "iNeuron" in your set**"""

set1 = {123,123,123,234,235,356}

set1 = list(set1)
set1.append("iNeuron")
print(set1)
set1 = set(set1)
print(type(set1))

"""**Q48. Try to add multiple values using add() function.**


"""

set1 = {123,123,123,234,235,356}

#set1 = list(set1)
#set1.append("iNeuron")
set1.add("preeta")
set1.add("payal went to goa")
#set1.update(1)
print(set1)
set1 = set(set1)
print(type(set1))

"""**Q49. How is update() different from add()?**

We use add() method to add single value to a set. We use update() method to add sequence values to a set. Here Sequences are any iterables including list , tuple , string , dict etc

**Q50. What is clear() in sets?**

The clear() method removes all elements in a set. Syntax. set.clear().

Q51. What is frozen set?

 A frozenset object is an immutable, unordered data type. A frozenset contains unique values, which makes it very similar to set data type. It is immutable like tuples.

Q52. How is frozen set different from set?
Frozenset is similar to set in Python, except that frozensets are immutable, which implies that once generated, elements from the frozenset cannot be added or removed.

Q53. What is union() in sets? Explain via code.
union () return all the values from both the sets in a result set . 

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.union(y) 

print(z)

Q54. What is intersection() in sets? Explain via code.

intersection() return only the common values from the both the sets into a result set . 

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.intersection(y) 

print(z)

Q55. What is dictionary ibn Python?

Dictionary is a collection data type in python 
in which data is stored in the form of key value pair 

duplicate keys are not allowed 
duplicate values are allowed 
unordered data 
dictionary by natyre is growable 
it is mutable

Q56. How is dictionary different from all other data structures.

The dictionary Data Structure in Python is an unordered collection of items. While other Data Structures use only one value as the element, the dictionary is a slightly more compound data structure. It makes use of two elements i.e. a pair of elements, namely, a key and a value

Q57. How can we delare a dictionary in Python?

 we can declare dictonary in the {key : value }
 code:

 thisdict = {
  "brand": "Ford",
  "electric": False,
  "year": 1964,
  "colors": ["red", "white", "blue"]
}

print(thisdict)

Q58. What will the output of the following?

var = {}
print(type(var))

ANS:
<class 'dict'>

Q59. How can we add an element in a dictionary?

using update () method 

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.update({"color": "red"})

-------------------------------------------

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["colour"] = "red"
print(thisdict)

Q60. Create a dictionary and access all the values in that dictionary.
thisdict = {
  "brand": "Ford",
  "electric": False,
  "year": 1964,
  "colors": ["red", "white", "blue"]
}
print (thisdict.value())

Q61. Create a nested dictionary and access all the element in the inner dictionary.
-->

myfamily = {
  "child1" : {
    "name" : "Emil",
    "year" : 2004
  },
  "child2" : {
    "name" : "Tobias",
    "year" : 2007
  },
  "child3" : {
    "name" : "Linus",
    "year" : 2011
  }
}

print(myfamily)

Q62. What is the use of get() function?
 -->
 get() function is use to acess the value of a specific key from the dictionary 

 thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

z = thisdict.get("model")
print(z)

Q63. What is the use of items() function?


It is use to get the items of the dictionary 

car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.items()

print(x)

Q64. What is the use of pop() function?

pop() function is use to remove the item 
----- code ---
fruits = ['apple', 'banana', 'cherry']

fruits.pop(1)

print(fruits)

Q65. What is the use of popitems() function?

popitem() is use to pop out the last item in the dict. 

dict1 = {
  "color" : ["red" , "green " , "purple"],

  "brand" : ["gucci","prada","armani"],

  "name": "monkey"
}
dict1.popitem()
print (dict1)

Q66. What is the use of keys() function?

---> key() is use to get the keys  from the dictionary items .
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.keys()

print(x)

Q67. What is the use of values() function?

values () function is use to only values of the items in the dictionary nor the keys.


  dict1 = {
  "color" : ["red" , "green " , "purple"],

  "brand" : ["gucci","prada","armani"],

  "name": "monkey"
}

a = dict1.keys()
print(a)

Q68. What are loops in Python?

repeating something over and over until a particular condition is satisfied.
python loops : for loop , while loop , do while loop .

70. What is the difference between for and while loops?

--->

for loop : it checks first the condition , if the condition matches then only it will perform the function defind inside the loop . 

while loop : it first runs the items inside the loops then check for the condtion .

The major difference between for loop and the while loop is that for loop is used when the number of iterations is known, whereas execution is done in the while loop until the statement in the program is proved wrong.

Q71. What is the use of continue statement?

continue statement:  is use to end the current iteration and continue with the next iteration

Q72. What is the use of break statement?

break statemnt : is use to break the loop and excecute the next statement which is out of loop

Q73. What is the use of pass statement?

pass statement is use whenwe declare the function first , but  we have to write the body of function later , till that time to excetute the program  and   to not give any error at the run time ,  we use pass statement inside the function to get rid of runtime error while exceution of code . 
and we can complte that  part of code later .

Q74. What is the use of range() function?

range() function is use to define the range like from 0 to 10  . 

for example we want to print the number between the range 1 to 100 then we can define by using arange function 

code ----------

for i in range (0 , 11):
  print(i)

Q75. How can you loop over a dictionary?

---------->

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
for x in thisdict:
  print(x)

Q76. Write a Python program to find the factorial of a given number



```
num = int(input("Enter a number: "))    
factorial = 1 
for i in range(1,num + 1):    
       factorial = factorial*i
print(factorial)
```

Q77. Write a Python program to calculate the simple interest. Formula to calculate simple interest is SI = (PRT)/100


```
# This is formatted as code
P = int(input("enter principle amount find out a simple intrest of "))
R = int(input("enter  the rate on intrest "))
T = int(input("enter the time "))

SI = (P*R*T)/100
print(SI) 
```

Q78. Write a Python program to calculate the compound interest. Formula of compound interest is A = P(1+ R/100)^t.



```
# This is formatted as code
P = int(input("enter principle amount find out a simple intrest of "))
R = int(input("enter  the rate on intrest "))
T = int(input("enter the time "))
A = (P*(1+ (R/100)))**T
CI = A - P
print(CI) 


```

Q79. Write a Python program to check if a number is prime or not.



```
# This is formatted as code
num = int(input("enter any number"))
for i in range(2 , num):
  if (num % i == 0 ):
    print("number is not prime ")
else:
  print("number is prime")    
```

Q80. Write a Python program to check Armstrong Number.

armstrong number is a number , total num of digitss in a number , so the summation of power of each digit of that number by total number of digits  is equal to that number then that number is called as armstrong number .

ex . 153 = 1**3 + 5**3 + 3**3 = 153 

soo 153 is called as a amrmstrong number 


```

num = int(input("enter any number here :")) #153
order = len(str(num))
sum = 0 
temp = num

while(temp >0 ):
    digit = temp % 10 # 153%10  will give 3 so digit = 3
    cube = digit**order
    sum = sum + cube
    fd = temp // 10 
    temp = fd

if sum == num :
    print(num , "is an armstrong number ")   
else :
    print(num , "not an armstrong number")   


```

Q81. Write a Python program to find the n-th Fibonacci Number.

fibonacci series : 12358

```
num = int(input("enter any number here :"))
num1 =0 
num2= 1
print(num1)
print(num2)
for i in range(1 , num+1):
    fibbo = num1+ num2  # 1 
    num1 = num2
    num2 = fibbo
    print(fibbo)

         
         


```

Q82. Write a Python program to interchange the first and last element in a list.




```
# This is formatted as code

def numswap():
    list1 = list(input("enter number in a list "))
    num1 = list1[0]
    num2 = list1[-1]
    list1[0] = num2
    list1[-1] = num1
    print(list1)
numswap()
```

Q83. Write a Python program to swap two elements in a list.



```
# This is formatted as code
def numswap():
    list1 = list(input("enter number in a list "))
    num1 = list1[0]
    num2 = list1[-1]
    list1[0] = num2
    list1[-1] = num1
    print(list1)
numswap()
```

Q84. Write a Python program to find N largest element from a list.



```
# This is formatted as code
def LargestNum():
    list1 = []
    n = int(input("total number u want in list "))
    for i in range(0,n+1):
        num = int(input("enter any number"))
        list1.append(num)
    print(list1)    
    
    max = list1[0]  
    for i in list1:
        if(i > max):
            max = i
    print(max,"is the largest number in the list ")
LargestNum()
```

Q85. Write a Python program to find cumulative sum of a list.

cumulative sum of list means ⁉
given_list = [10 , 20 , 30 , 40 , 50 ]
cumulative_list = [10 , 30 , 60 , 100 , 150 ]

```
# This is formatted as code

def cumulative_sum():
    list1 = []
    n = int(input("total number u want in list "))
    for i in range(0,n+1):
        num = int(input("enter any number"))
        list1.append(num)
    print(list1) 
    new_list = []
    sum = 0 
    for i in list1:
        sum = sum + i 
        new_list.append(sum) 
    print(new_list)    

cumulative_sum()
```

Q86. Write a Python program to check if a string is palindrome or not.

palindrome1 = "madam"


```

str1 = input("enter any string to check if it is palindrome or not \n")
str2 = str1[ : : -1]
print(str2)
if (str1 == str2):
    print(str1 , "is a palindrome")
else:
    print(str1, "is not a palindrome")    


```

Q87. Write a Python program to remove i'th element from a string.


```
def removeEle():
    str1 = input("enter any string value \n")
    str2 = int(input("which ele you want to remove"))
    a = str1[0:str2-1]     
    b = str1[str2:]  
    print(a+b)
removeEle()
```

Q88. Write a Python program to check if a substring is present in a given string.



```
def substringPresent():
    str1 = input("enter any string ")
    substring1 = input("enter the substring")
    if(str1.find(substring1)>0):
        print(" substring is present in th estring ")
    else:
        print("substring is not present in the main string")   
substringPresent() 

```

Q89. Write a Python program to find words which are greater than given length k



```
# This is formatted as code
word = input("enter any string ")
l = len(word)
k = int(input("enter the length of word you want "))
if(l>k):
    print(word, "is greter than given length")
else:
    print("word is shorter than given length")
```

Q90. Write a Python program to extract unique dictionary values.



```
# This is formatted as code
dict1 = {"colour":"black and white",
          "model":"tata nexon",
           "name":"nikita",
           "owner":"nikita"
         }
print(set(dict1.values()))

#### set dosent allow duplication .

```

Q91. Write a Python program to merge two dictionary.


```
# This is formatted as code
dict1 = {"colour":"black and white",
          "model":"tata nexon",
           "name":"nikita",
           "owner":"nikita"
         }
dict2 ={"brand": "Ford",
  "model": "Mustang",
  "year": 1964}

dict3 = (dict1|dict2)
print(dict3)
```

Q92. Write a Python program to convert a list of tuples into dictionary.

Input : [('Sachin', 10), ('MSD', 7), ('Kohli', 18), ('Rohit', 45)]
Output : {'Sachin': 10, 'MSD': 7, 'Kohli': 18, 'Rohit': 45}




```
# This is formatted as code
list1 = [('Sachin', 10), ('MSD', 7), ('Kohli', 18), ('Rohit', 45)]
print(list1)
#Output : {'Sachin': 10, 'MSD': 7, 'Kohli': 18, 'Rohit': 45}
res = dict(list1)
print (res)
```

Q93. Write a Python program to create a list of tuples from given list having number and its cube in each tuple.

Input: list = [9, 5, 6]
Output: [(9, 729), (5, 125), (6, 216)]


```
# This is formatted as code
list1 = [9, 5, 6]
#Output: [(9, 729), (5, 125), (6, 216)]
list2 = []

for i in list1:
    cube = i * i * i 
    res =  (i , cube)
    list2.append((res))
    
print(list2)
```

Q94. Write a Python program to get all combinations of 2 tuples.

Input : test_tuple1 = (7, 2), test_tuple2 = (7, 8)
Output : [(7, 7), (7, 8), (2, 7), (2, 8), (7, 7), (7, 2), (8, 7), (8, 2)]




```
test_tuple1 = (7,2)
test_tuple2 = (7,8)
print("tuple1:",test_tuple1)
print("tuple2 :",test_tuple2)
res = [(a,b)for a in test_tuple1 for b in test_tuple2] + [(a,b) for a in test_tuple2 for b in test_tuple1]
print("all possible combination of both the tuples are : \n ",res)
```

Q95. Write a Python program to sort a list of tuples by second item.

Input : [('for', 24), ('Geeks', 8), ('Geeks', 30)] 
Output : [('Geeks', 8), ('for', 24), ('Geeks', 30)]

```
# This is formatted as code
list1 = [('for', 24), ('Geeks', 8), ('Geeks', 30)] 
#Output : [('Geeks', 8), ('for', 24), ('Geeks', 30)]
res = (sorted(list1, (sorted(tup, key = lambda x: x[1]))))
print(res)
```

Q96. Write a python program to print below pattern.

* 
* * 
* * * 
* * * * 
* * * * * 



```
# This is formatted as code
for i in range(1,6):
    for j in range(1,i+1):
        print("*" , end="")
    print("\n")    
```

Q97. Write a python program to print below pattern.

    *
   **
  ***
 ****
*****

```
# This is formatted as 
for i in range(1,6): #1
    for k in range(1,6-i): #(1,4)
        print(" ",end="")
    for j in range(1,i+1): #(1,2)
        print("*", end='')
    print("\n")    
```

Q98. Write a python program to print below pattern.

    * 
   * * 
  * * * 
 * * * * 
* * * * * 


```
# This is formatted as code
for i in range(1,6):
    for k in range(1,7-i-1):
        print(" ",end="")
    for j in range(1,i+1):
        print("*", end=' ')
    print("\n")
```

Q99. Write a python program to print below pattern.

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5


```
# This is formatted as code
for i in range(1,6): # 1
    for j in range(1,i+1): #1
        print( j , end=" ")
    print("\n") 
```

Q100. Write a python program to print below pattern.

A 
B B 
C C C 
D D D D 
E E E E E 


```
# This is formatted as code
for i in range(65,5+65): 
    for j in range(65,i+1): 
        print( chr(i) , end=" ")
    print("\n")  

```
# This is formatted as code
```



```
"""